version: "3"

services:
  mysql:
    image: mysql:8
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=golang
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=123456
    volumes:
      - golang-data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 500M
    depends_on:
      - mysql
    ports:
      - "1511:80"
  # backend:
  #   image: backend:dev
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "9090:8080"
volumes:
  golang-data:
